//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("API.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///    &lt;body&gt;
        ///        &lt;p style=&quot;font-family: Google Sans, Roboto, Arial, Helvetica, sans-serif;
        ///              font-size: 16px;&quot;&gt;Password reset has been requested for this account. Please proceed by clicking the button below&lt;/p&gt;
        ///
        ///        
        ///&lt;a href=&quot;{0}&quot; target=&quot;_blank&quot; role=&quot;button&quot; 
        ///            style=&quot;mso-hide:all; padding: 0px 15px; font: 500 16px/36px Google Sans, Roboto, Arial, Helvetica, sans-serif; border: none; border-radius: 10px; box-sizing: border-box; display: inline-b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForgotPasswordBody {
            get {
                return ResourceManager.GetString("ForgotPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset requested.
        /// </summary>
        public static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///    &lt;body&gt;
        ///        &lt;p style=&quot;font-family: Google Sans, Roboto, Arial, Helvetica, sans-serif;
        ///              font-size: 16px;&quot;&gt;Please confirm your registration by clicking the button below&lt;/p&gt;
        ///
        ///        
        ///&lt;a href=&quot;{0}&quot; target=&quot;_blank&quot; role=&quot;button&quot; 
        ///            style=&quot;mso-hide:all; padding: 0px 15px; font: 500 16px/36px Google Sans, Roboto, Arial, Helvetica, sans-serif; border: none; border-radius: 10px; box-sizing: border-box; display: inline-block; text-decoration: none;backgr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SignUpConfirmationEmailBody {
            get {
                return ResourceManager.GetString("SignUpConfirmationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm registration.
        /// </summary>
        public static string SignUpConfirmationEmailSubject {
            get {
                return ResourceManager.GetString("SignUpConfirmationEmailSubject", resourceCulture);
            }
        }
    }
}
